/** Paid, isolated door/arch mask experiment; never applies changes to a map. */
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import sharp from 'sharp';import {createHash} from 'node:crypto';
const [sourcePath,outputPath]=process.argv.slice(2);if(!sourcePath||!outputPath)throw Error('Usage: node --import tsx generate_door_arch_test.mts SOURCE OUTPUT');
const out=path.resolve(outputPath);await fs.mkdir(out,{recursive:true});process.env.DATA_ROOT=await fs.mkdtemp(path.join(os.tmpdir(),'dnd-arch-mask-'));process.env.DM_PASSPHRASE='isolated-arch-test';
const {config}=await import('../../src/config.js');if(!config.geminiApiKey){for(const file of ['server/data/settings.json','C:/Users/vcons/DnD-App-v2/server/data/settings.json'])try{const settings=JSON.parse(await fs.readFile(file,'utf8'));if(settings.geminiApiKey){config.geminiApiKey=settings.geminiApiKey;break;}}catch{}}
if(!config.geminiApiKey)throw Error('Configure the image API before running this test');
const {generateApiImage}=await import('../../src/ai/imageGateway.js');
const original=await fs.readFile(sourcePath),meta=await sharp(original).metadata();if(!meta.width||!meta.height)throw Error('Invalid source image');await fs.writeFile(out+'/original.png',original);
const prompt='Annotate this battle map. Mark visible wooden or metal door leaves with bright cyan (#00FFFF) straight lines from jamb to jamb, about 8 pixels thick. Paint only CLEAR overhead stone arch spans solid magenta (#FF00FF), edge to edge: a supported bridge of stone with a visible opening and walkable floor beneath. Broken, lowered or notched wall tops are not arches. If a possible arch is genuinely ambiguous, mark its stone span orange (#FF8800) instead of magenta. Do not mark supports, walls or vertical stone faces. Keep the floor beneath each arch unmarked. Ignore rubble, shadows, stairs, furniture and ordinary empty openings. Preserve all other map pixels, exact framing and aspect ratio. No labels or invented structures.';
const start=Date.now(),reference=await sharp(original).rotate().png().toBuffer(),result=await generateApiImage(prompt,{width:2048,height:Math.round(2048*meta.height/meta.width)},[{mimeType:'image/png',data:reference.toString('base64')}]);if('error' in result)throw Error(result.error);
const bytes=await fs.readFile(path.join(config.uploadsDir,path.basename(result.path))),file='door-arch-mask-v4'+path.extname(result.path);await fs.writeFile(out+'/'+file,bytes);await fs.writeFile(out+'/api-receipt-v4.json',JSON.stringify({model:config.geminiImageModel,prompt,elapsedSeconds:(Date.now()-start)/1000,sourceSha256:createHash('sha256').update(original).digest('hex'),maskSha256:createHash('sha256').update(bytes).digest('hex'),file,metadata:await sharp(bytes).metadata(),manualEdits:false,experimentalOnly:true},null,2));console.log('Saved '+out+'/'+file);
