import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
import {NodeIO} from '@gltf-transform/core';import {ALL_EXTENSIONS} from '@gltf-transform/extensions';import {simplify,weld} from '@gltf-transform/functions';import {MeshoptSimplifier} from 'meshoptimizer';
import sharp from 'sharp';
const [input,destination]=process.argv.slice(2);if(!input||!destination)throw Error('Usage: node reduce.mjs INPUT.glb NEW_OUTPUT_DIRECTORY');
const policy={id:'monster-reduction-v1',targetTriangles:20000,errorLimit:.01,colorEncoding:'jpeg',quality:95,chromaSubsampling:'4:4:4',resize:false,geometryCompression:false};
const start=performance.now(),source=await fs.readFile(input),hash=b=>createHash('sha256').update(b).digest('hex');await MeshoptSimplifier.ready;const io=new NodeIO().registerExtensions(ALL_EXTENSIONS);const doc=await io.read(input);if(doc.getRoot().listAnimations().length||doc.getRoot().listSkins().length)throw Error('Static meshes only');
function audit(d){let triangles=0;for(const mesh of d.getRoot().listMeshes())for(const p of mesh.listPrimitives()){if(p.getMode()!==4||!p.getIndices())throw Error('Indexed triangles required');const pos=p.getAttribute('POSITION');for(const v of pos.getArray())if(!Number.isFinite(v))throw Error('Nonfinite position');for(const i of p.getIndices().getArray())if(i>=pos.getCount())throw Error('Invalid index');triangles+=p.getIndices().getCount()/3;}return triangles;}
const originalTriangles=audit(doc),textures=[];
for(const [index,t] of doc.getRoot().listTextures().entries()){
 const before=Buffer.from(t.getImage()),meta=await sharp(before).metadata();let color=false,data=false;
 for(const m of doc.getRoot().listMaterials()){color ||=m.getBaseColorTexture()===t;data ||=[m.getNormalTexture(),m.getMetallicRoughnessTexture(),m.getOcclusionTexture(),m.getEmissiveTexture()].includes(t);}
 let action='preserved';let bytes=before;if(color&&!data){const raw=await sharp(before).ensureAlpha().raw().toBuffer();let opaque=true;for(let i=3;i<raw.length;i+=4)if(raw[i]!==255){opaque=false;break;}
 if(opaque){const candidate=await sharp(before).jpeg({quality:95,chromaSubsampling:'4:4:4',mozjpeg:true}).toBuffer();if(candidate.length<before.length){bytes=candidate;t.setImage(bytes).setMimeType('image/jpeg');action='jpeg95';}}}
 const after=await sharp(bytes).metadata();if(meta.width!==after.width||meta.height!==after.height)throw Error('Texture resized');textures.push({index,action,width:meta.width,height:meta.height,beforeBytes:before.length,afterBytes:bytes.length,sha256:hash(bytes)});
}
const simplifyStart=performance.now();if(originalTriangles>20000)await doc.transform(weld(),simplify({simplifier:MeshoptSimplifier,ratio:20000/originalTriangles,error:.01}));const simplifyMs=performance.now()-simplifyStart;
await fs.mkdir(destination,{recursive:false});const temp=path.join(destination,'model.pending.glb');await io.write(temp,doc);const check=await io.read(temp);const triangles=audit(check);if(triangles>originalTriangles)throw Error('Triangle count increased');for(const [i,t] of check.getRoot().listTextures().entries())if(hash(t.getImage())!==textures[i].sha256)throw Error('Texture changed on export');if(hash(await fs.readFile(input))!==hash(source))throw Error('Source modified');
const bytes=await fs.readFile(temp);await fs.rename(temp,path.join(destination,'model.glb'));const receipt={policy,source:path.resolve(input),sourceSha256:hash(source),sourceBytes:source.length,originalTriangles,triangles,bytes:bytes.length,reductionPercent:100*(1-bytes.length/source.length),sha256:hash(bytes),textures,simplifyMs,totalMs:performance.now()-start,peakRssMiB:process.resourceUsage().maxRSS/1024,versions:{gltfTransform:'4.5.0',meshoptimizer:'1.2.0',sharp:sharp.versions.sharp},validation:'export reloaded; finite positions; indices in range; textures unchanged on export; source preserved',targetReached:triangles<=20000};await fs.writeFile(path.join(destination,'receipt.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt,null,2));
