import type { CreatureTemplate } from '../../../shared/types.js';

/**
 * A curated, offline subset of the 5e SRD bestiary so standard-creature search
 * works with zero network/keys. Gemini (creatures/gemini.ts) covers anything
 * not listed here.
 *
 * EVERY entry is COMPLETE — `level` (Challenge Rating), `armorClass`, `speed`,
 * `stats`, and `actions` are all REQUIRED — so a creature added from search comes
 * with a full stat block + attacks at its CANONICAL power level (a Goblin stays a
 * weak CR 1/4, never an inflated version). HP values are the SRD averages; attack
 * lines use the "+N to hit, XdY+Z type" shape the insert step parses into rollable
 * weapons. Themed/custom variants (a "Stone Goblin") are generated by the AI,
 * grounded on the nearest base creature here so they scale UP from it.
 */
type Stats = { STR: number; DEX: number; CON: number; INT: number; WIS: number; CHA: number };
type SrdEntry = {
  name: string;
  creatureType: string;
  /** Challenge Rating = intended power level (1/8 = 0.125, 1/4 = 0.25, 1/2 = 0.5). */
  level: number;
  maxHp: number;
  armorClass: number;
  speed: string;
  stats: Stats;
  resistances: string[];
  weaknesses: string[];
  actions: { name: string; description: string }[];
  abilities: { name: string; description: string }[];
};

const SRD: SrdEntry[] = [
  // ---- Humanoids ----
  { name: 'Goblin', creatureType: 'humanoid (goblinoid)', level: 0.25, maxHp: 7, armorClass: 15, speed: '30 ft.', stats: { STR: 8, DEX: 14, CON: 10, INT: 10, WIS: 8, CHA: 8 }, resistances: [], weaknesses: [], actions: [{ name: 'Scimitar', description: '+4 to hit, 1d6+2 slashing.' }, { name: 'Shortbow', description: '+4 to hit, range 80/320, 1d6+2 piercing.' }], abilities: [{ name: 'Nimble Escape', description: 'Can Disengage or Hide as a bonus action.' }] },
  { name: 'Hobgoblin', creatureType: 'humanoid (goblinoid)', level: 0.5, maxHp: 11, armorClass: 18, speed: '30 ft.', stats: { STR: 13, DEX: 12, CON: 12, INT: 10, WIS: 10, CHA: 9 }, resistances: [], weaknesses: [], actions: [{ name: 'Longsword', description: '+3 to hit, 1d8+1 slashing (1d10+1 two-handed).' }, { name: 'Longbow', description: '+3 to hit, range 150/600, 1d8+1 piercing.' }], abilities: [{ name: 'Martial Advantage', description: 'Once per turn, +2d6 damage to a creature it hits that is within 5 ft of an ally.' }] },
  { name: 'Orc', creatureType: 'humanoid (orc)', level: 0.5, maxHp: 15, armorClass: 13, speed: '30 ft.', stats: { STR: 16, DEX: 12, CON: 16, INT: 7, WIS: 11, CHA: 10 }, resistances: [], weaknesses: [], actions: [{ name: 'Greataxe', description: '+5 to hit, 1d12+3 slashing.' }, { name: 'Javelin', description: '+5 to hit, range 30/120, 1d6+3 piercing.' }], abilities: [{ name: 'Aggressive', description: 'Bonus action move toward a hostile creature it can see.' }] },
  { name: 'Kobold', creatureType: 'humanoid (kobold)', level: 0.125, maxHp: 5, armorClass: 12, speed: '30 ft.', stats: { STR: 7, DEX: 15, CON: 9, INT: 8, WIS: 7, CHA: 8 }, resistances: [], weaknesses: [], actions: [{ name: 'Dagger', description: '+4 to hit, 1d4+2 piercing.' }, { name: 'Sling', description: '+4 to hit, range 30/120, 1d4+2 bludgeoning.' }], abilities: [{ name: 'Pack Tactics', description: 'Advantage on attacks if an ally is within 5 ft of the target.' }, { name: 'Sunlight Sensitivity', description: 'Disadvantage on attacks and sight Perception in sunlight.' }] },
  { name: 'Bandit', creatureType: 'humanoid', level: 0.125, maxHp: 11, armorClass: 12, speed: '30 ft.', stats: { STR: 11, DEX: 12, CON: 12, INT: 10, WIS: 10, CHA: 10 }, resistances: [], weaknesses: [], actions: [{ name: 'Scimitar', description: '+3 to hit, 1d6+1 slashing.' }, { name: 'Light Crossbow', description: '+3 to hit, range 80/320, 1d8+1 piercing.' }], abilities: [] },
  { name: 'Guard', creatureType: 'humanoid', level: 0.125, maxHp: 11, armorClass: 16, speed: '30 ft.', stats: { STR: 13, DEX: 12, CON: 12, INT: 10, WIS: 11, CHA: 10 }, resistances: [], weaknesses: [], actions: [{ name: 'Spear', description: '+3 to hit, range 20/60, 1d6+1 piercing (1d8+1 two-handed).' }], abilities: [] },
  { name: 'Cultist', creatureType: 'humanoid', level: 0.125, maxHp: 9, armorClass: 12, speed: '30 ft.', stats: { STR: 11, DEX: 12, CON: 10, INT: 10, WIS: 11, CHA: 10 }, resistances: [], weaknesses: [], actions: [{ name: 'Scimitar', description: '+3 to hit, 1d6+1 slashing.' }], abilities: [{ name: 'Dark Devotion', description: 'Advantage on saves against being charmed or frightened.' }] },
  { name: 'Bugbear', creatureType: 'humanoid (goblinoid)', level: 1, maxHp: 27, armorClass: 16, speed: '30 ft.', stats: { STR: 15, DEX: 14, CON: 13, INT: 8, WIS: 11, CHA: 9 }, resistances: [], weaknesses: [], actions: [{ name: 'Morningstar', description: '+4 to hit, 2d8+2 piercing.' }, { name: 'Javelin', description: '+4 to hit, range 30/120, 1d6+2 piercing.' }], abilities: [{ name: 'Brute', description: 'Extra die of damage on its melee weapon hits (already included).' }, { name: 'Surprise Attack', description: 'On a surprise-round hit, +2d6 damage.' }] },
  { name: 'Gnoll', creatureType: 'humanoid (gnoll)', level: 0.5, maxHp: 22, armorClass: 15, speed: '30 ft.', stats: { STR: 14, DEX: 12, CON: 11, INT: 6, WIS: 10, CHA: 7 }, resistances: [], weaknesses: [], actions: [{ name: 'Spear', description: '+4 to hit, 1d6+2 piercing (1d8+2 two-handed).' }, { name: 'Bite', description: '+4 to hit, 1d4+2 piercing.' }, { name: 'Longbow', description: '+3 to hit, range 150/600, 1d8+1 piercing.' }], abilities: [{ name: 'Rampage', description: 'Bonus action move + bite after reducing a creature to 0 HP.' }] },

  // ---- Undead ----
  { name: 'Skeleton', creatureType: 'undead', level: 0.25, maxHp: 13, armorClass: 13, speed: '30 ft.', stats: { STR: 10, DEX: 14, CON: 15, INT: 6, WIS: 8, CHA: 5 }, resistances: [], weaknesses: ['bludgeoning'], actions: [{ name: 'Shortsword', description: '+4 to hit, 1d6+2 piercing.' }, { name: 'Shortbow', description: '+4 to hit, range 80/320, 1d6+2 piercing.' }], abilities: [{ name: 'Undead', description: 'Immune to poison and exhaustion; vulnerable to bludgeoning.' }] },
  { name: 'Zombie', creatureType: 'undead', level: 0.25, maxHp: 22, armorClass: 8, speed: '20 ft.', stats: { STR: 13, DEX: 6, CON: 16, INT: 3, WIS: 6, CHA: 5 }, resistances: [], weaknesses: [], actions: [{ name: 'Slam', description: '+3 to hit, 1d6+1 bludgeoning.' }], abilities: [{ name: 'Undead Fortitude', description: 'On reduction to 0 HP (not radiant/crit), CON save DC 5 + damage to drop to 1 HP instead.' }] },
  { name: 'Ghoul', creatureType: 'undead', level: 1, maxHp: 22, armorClass: 12, speed: '30 ft.', stats: { STR: 13, DEX: 15, CON: 10, INT: 7, WIS: 10, CHA: 6 }, resistances: [], weaknesses: [], actions: [{ name: 'Bite', description: '+2 to hit, 2d6+2 piercing.' }, { name: 'Claws', description: '+4 to hit, 2d4+2 slashing; a non-elf target makes a DC 10 CON save or is paralyzed for 1 minute.' }], abilities: [{ name: 'Paralyzing Claws', description: 'Targets hit by the claws must save or be paralyzed.' }] },
  { name: 'Ghost', creatureType: 'undead', level: 4, maxHp: 45, armorClass: 11, speed: 'fly 40 ft. (hover)', stats: { STR: 7, DEX: 13, CON: 10, INT: 10, WIS: 12, CHA: 17 }, resistances: ['acid', 'fire', 'lightning', 'thunder', 'nonmagical bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Withering Touch', description: '+5 to hit, 4d6+3 necrotic.' }, { name: 'Horrifying Visage', description: 'Each creature within 60 ft that can see it makes a DC 13 WIS save or is frightened for 1 minute.' }], abilities: [{ name: 'Incorporeal Movement', description: 'Can move through objects and creatures (1d10 force if it ends inside one).' }] },
  { name: 'Wight', creatureType: 'undead', level: 3, maxHp: 45, armorClass: 14, speed: '30 ft.', stats: { STR: 15, DEX: 14, CON: 16, INT: 10, WIS: 13, CHA: 15 }, resistances: ['necrotic', 'nonmagical bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes two longsword attacks, or one longsword and one Life Drain.' }, { name: 'Longsword', description: '+4 to hit, 1d8+2 slashing (1d10+2 two-handed).' }, { name: 'Life Drain', description: '+4 to hit, 1d6+2 necrotic; target makes a DC 13 CON save or its max HP is reduced by the damage.' }], abilities: [{ name: 'Sunlight Sensitivity', description: 'Disadvantage on attacks and sight Perception in sunlight.' }] },
  { name: 'Specter', creatureType: 'undead', level: 1, maxHp: 22, armorClass: 12, speed: 'fly 50 ft. (hover)', stats: { STR: 1, DEX: 14, CON: 11, INT: 10, WIS: 10, CHA: 11 }, resistances: ['necrotic', 'cold', 'nonmagical bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Life Drain', description: '+4 to hit, 3d6 necrotic; target makes a DC 10 CON save or its max HP is reduced by the damage.' }], abilities: [{ name: 'Incorporeal Movement', description: 'Can move through objects and creatures.' }, { name: 'Sunlight Sensitivity', description: 'Disadvantage on attacks and sight Perception in sunlight.' }] },
  { name: "Will-o'-Wisp", creatureType: 'undead', level: 2, maxHp: 22, armorClass: 19, speed: 'fly 50 ft. (hover)', stats: { STR: 1, DEX: 28, CON: 10, INT: 13, WIS: 14, CHA: 11 }, resistances: ['lightning', 'cold', 'necrotic', 'nonmagical bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Shock', description: '+4 to hit, 2d8 lightning.' }], abilities: [{ name: 'Consume Life', description: 'Can drain the life of a nearby creature at 0 HP (DC 10 CON or die).' }, { name: 'Variable Illumination', description: 'Sheds 5–20 ft of dim light; can turn fully invisible.' }] },

  // ---- Beasts ----
  { name: 'Wolf', creatureType: 'beast', level: 0.25, maxHp: 11, armorClass: 13, speed: '40 ft.', stats: { STR: 12, DEX: 15, CON: 12, INT: 3, WIS: 12, CHA: 6 }, resistances: [], weaknesses: [], actions: [{ name: 'Bite', description: '+4 to hit, 2d4+2 piercing; target makes a DC 11 STR save or is knocked prone.' }], abilities: [{ name: 'Pack Tactics', description: 'Advantage on attacks if an ally is within 5 ft of the target.' }] },
  { name: 'Dire Wolf', creatureType: 'beast', level: 1, maxHp: 37, armorClass: 14, speed: '50 ft.', stats: { STR: 17, DEX: 15, CON: 15, INT: 3, WIS: 12, CHA: 7 }, resistances: [], weaknesses: [], actions: [{ name: 'Bite', description: '+5 to hit, 2d6+3 piercing; target makes a DC 13 STR save or is knocked prone.' }], abilities: [{ name: 'Pack Tactics', description: 'Advantage on attacks if an ally is within 5 ft of the target.' }] },
  { name: 'Brown Bear', creatureType: 'beast', level: 1, maxHp: 34, armorClass: 11, speed: '40 ft., climb 30 ft.', stats: { STR: 19, DEX: 10, CON: 16, INT: 2, WIS: 13, CHA: 7 }, resistances: [], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes one bite and one claws attack.' }, { name: 'Bite', description: '+6 to hit, 1d8+4 piercing.' }, { name: 'Claws', description: '+6 to hit, 2d6+4 slashing.' }], abilities: [{ name: 'Keen Smell', description: 'Advantage on Perception checks that rely on smell.' }] },
  { name: 'Giant Spider', creatureType: 'beast', level: 1, maxHp: 26, armorClass: 14, speed: '30 ft., climb 30 ft.', stats: { STR: 14, DEX: 16, CON: 12, INT: 2, WIS: 11, CHA: 4 }, resistances: [], weaknesses: [], actions: [{ name: 'Bite', description: '+5 to hit, 1d8+3 piercing; DC 11 CON save, 2d8 poison (half on save).' }, { name: 'Web (Recharge 5–6)', description: 'Range 30/60, DC 12 DEX save or restrained by webbing.' }], abilities: [{ name: 'Spider Climb', description: 'Can climb difficult surfaces, including upside down.' }, { name: 'Web Walker', description: 'Knows the location of anything touching its web; ignores web movement restrictions.' }] },
  { name: 'Giant Rat', creatureType: 'beast', level: 0.125, maxHp: 7, armorClass: 12, speed: '30 ft.', stats: { STR: 7, DEX: 15, CON: 11, INT: 2, WIS: 10, CHA: 4 }, resistances: [], weaknesses: [], actions: [{ name: 'Bite', description: '+4 to hit, 1d4+2 piercing.' }], abilities: [{ name: 'Pack Tactics', description: 'Advantage on attacks if an ally is within 5 ft of the target.' }] },
  { name: 'Giant Bat', creatureType: 'beast', level: 0.25, maxHp: 22, armorClass: 13, speed: '10 ft., fly 60 ft.', stats: { STR: 15, DEX: 16, CON: 11, INT: 2, WIS: 12, CHA: 6 }, resistances: [], weaknesses: [], actions: [{ name: 'Bite', description: '+4 to hit, 1d6+2 piercing.' }], abilities: [{ name: 'Keen Hearing', description: 'Advantage on Perception checks that rely on hearing; has blindsight.' }] },
  { name: 'Boar', creatureType: 'beast', level: 0.25, maxHp: 11, armorClass: 11, speed: '40 ft.', stats: { STR: 13, DEX: 11, CON: 12, INT: 2, WIS: 9, CHA: 5 }, resistances: [], weaknesses: [], actions: [{ name: 'Tusk', description: '+3 to hit, 1d6+1 slashing.' }], abilities: [{ name: 'Relentless', description: 'If ≤7 damage would drop it to 0 HP, it drops to 1 instead (once per turn).' }, { name: 'Charge', description: 'After moving 20+ ft straight toward a target, +1d6 damage and DC 11 STR or prone.' }] },
  { name: 'Constrictor Snake', creatureType: 'beast', level: 0.25, maxHp: 13, armorClass: 12, speed: '30 ft., swim 30 ft.', stats: { STR: 15, DEX: 14, CON: 12, INT: 1, WIS: 10, CHA: 3 }, resistances: [], weaknesses: [], actions: [{ name: 'Bite', description: '+4 to hit, 1d6+2 piercing.' }, { name: 'Constrict', description: '+4 to hit, 1d8+2 bludgeoning; the target is grappled (escape DC 14) and restrained.' }], abilities: [] },

  // ---- Monstrosities / constructs / oozes ----
  { name: 'Owlbear', creatureType: 'monstrosity', level: 3, maxHp: 59, armorClass: 13, speed: '40 ft.', stats: { STR: 20, DEX: 12, CON: 17, INT: 3, WIS: 12, CHA: 7 }, resistances: [], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes one beak and one claws attack.' }, { name: 'Beak', description: '+7 to hit, 1d10+5 piercing.' }, { name: 'Claws', description: '+7 to hit, 2d8+5 slashing.' }], abilities: [{ name: 'Keen Sight & Smell', description: 'Advantage on Perception using sight or smell.' }] },
  { name: 'Mimic', creatureType: 'monstrosity', level: 2, maxHp: 58, armorClass: 12, speed: '15 ft.', stats: { STR: 17, DEX: 12, CON: 15, INT: 5, WIS: 13, CHA: 8 }, resistances: ['acid'], weaknesses: [], actions: [{ name: 'Pseudopod', description: '+5 to hit, 1d8+3 bludgeoning; if disguised, the target is also subjected to Adhesive (grappled, escape DC 13).' }, { name: 'Bite', description: '+5 to hit, 1d8+3 piercing plus 1d8 acid.' }], abilities: [{ name: 'False Appearance', description: 'Indistinguishable from an ordinary object while it stays still.' }, { name: 'Adhesive', description: 'Adheres to anything that touches it; grapples on contact.' }] },
  { name: 'Animated Armor', creatureType: 'construct', level: 1, maxHp: 33, armorClass: 18, speed: '25 ft.', stats: { STR: 14, DEX: 11, CON: 13, INT: 1, WIS: 3, CHA: 1 }, resistances: ['poison', 'psychic'], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes two slam attacks.' }, { name: 'Slam', description: '+4 to hit, 1d6+2 bludgeoning.' }], abilities: [{ name: 'Antimagic Susceptibility', description: 'Incapacitated in an antimagic field; STR save vs dispel magic or fall unconscious.' }] },
  { name: 'Gelatinous Cube', creatureType: 'ooze', level: 2, maxHp: 84, armorClass: 6, speed: '15 ft.', stats: { STR: 14, DEX: 3, CON: 20, INT: 1, WIS: 6, CHA: 1 }, resistances: [], weaknesses: [], actions: [{ name: 'Pseudopod', description: '+4 to hit, 3d6 acid.' }, { name: 'Engulf', description: 'Moves through a creature’s space; DC 12 DEX save or be engulfed (3d6 acid/turn, restrained).' }], abilities: [{ name: 'Transparent', description: 'Hard to spot (DC 15 Perception) until it moves or attacks.' }] },

  // ---- Giants ----
  { name: 'Ogre', creatureType: 'giant', level: 2, maxHp: 59, armorClass: 11, speed: '40 ft.', stats: { STR: 19, DEX: 8, CON: 16, INT: 5, WIS: 7, CHA: 7 }, resistances: [], weaknesses: [], actions: [{ name: 'Greatclub', description: '+6 to hit, 2d8+4 bludgeoning.' }, { name: 'Javelin', description: '+6 to hit, range 30/120, 2d6+4 piercing.' }], abilities: [] },
  { name: 'Troll', creatureType: 'giant', level: 5, maxHp: 84, armorClass: 15, speed: '30 ft.', stats: { STR: 18, DEX: 13, CON: 20, INT: 7, WIS: 9, CHA: 7 }, resistances: [], weaknesses: ['fire', 'acid'], actions: [{ name: 'Multiattack', description: 'Makes one bite and two claw attacks.' }, { name: 'Bite', description: '+7 to hit, 1d6+4 piercing.' }, { name: 'Claw', description: '+7 to hit, 2d6+4 slashing.' }], abilities: [{ name: 'Regeneration', description: 'Regains 10 HP at the start of its turn unless it took fire or acid damage (and never at 0 HP).' }] },
  { name: 'Hill Giant', creatureType: 'giant', level: 5, maxHp: 105, armorClass: 13, speed: '40 ft.', stats: { STR: 21, DEX: 8, CON: 19, INT: 5, WIS: 9, CHA: 6 }, resistances: [], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes two greatclub attacks.' }, { name: 'Greatclub', description: '+8 to hit, 3d8+5 bludgeoning.' }, { name: 'Rock', description: '+8 to hit, range 60/240, 3d10+5 bludgeoning.' }], abilities: [] },

  // ---- Fiends / elementals / dragon ----
  { name: 'Imp', creatureType: 'fiend (devil)', level: 1, maxHp: 10, armorClass: 13, speed: '20 ft., fly 40 ft.', stats: { STR: 6, DEX: 17, CON: 13, INT: 11, WIS: 12, CHA: 14 }, resistances: ['cold', 'nonmagical non-silvered bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Sting', description: '+5 to hit, 1d4+3 piercing; DC 11 CON save, 3d6 poison (half on save).' }], abilities: [{ name: 'Shapechanger', description: 'Can transform into a rat, raven, or spider.' }, { name: 'Magic Resistance', description: 'Advantage on saves vs spells; sees in magical darkness.' }] },
  { name: 'Quasit', creatureType: 'fiend (demon)', level: 1, maxHp: 7, armorClass: 13, speed: '40 ft.', stats: { STR: 5, DEX: 17, CON: 10, INT: 7, WIS: 10, CHA: 10 }, resistances: ['fire', 'cold', 'lightning', 'nonmagical non-silvered bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Claws', description: '+4 to hit, 1d4+3 slashing; DC 10 CON save or poisoned for 1 minute.' }, { name: 'Scare (1/day)', description: 'One creature within 20 ft makes a DC 10 WIS save or is frightened for 1 minute.' }], abilities: [{ name: 'Shapechanger', description: 'Can transform into a bat, centipede, or toad.' }, { name: 'Magic Resistance', description: 'Advantage on saves against spells and magical effects.' }] },
  { name: 'Fire Elemental', creatureType: 'elemental', level: 5, maxHp: 102, armorClass: 13, speed: '50 ft.', stats: { STR: 10, DEX: 17, CON: 16, INT: 6, WIS: 10, CHA: 7 }, resistances: ['nonmagical bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes two touch attacks.' }, { name: 'Touch', description: '+6 to hit, 2d6+3 fire; the target ignites (1d10 fire at the start of its turns).' }], abilities: [{ name: 'Fire Form', description: 'Ignites flammables; a creature that hits it in melee takes 1d10 fire.' }, { name: 'Immunities', description: 'Immune to fire and poison; can’t be grappled or knocked prone.' }] },
  { name: 'Water Elemental', creatureType: 'elemental', level: 5, maxHp: 114, armorClass: 14, speed: '30 ft., swim 90 ft.', stats: { STR: 18, DEX: 14, CON: 18, INT: 5, WIS: 10, CHA: 8 }, resistances: ['acid', 'nonmagical bludgeoning/piercing/slashing'], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes two slam attacks.' }, { name: 'Slam', description: '+7 to hit, 2d8+4 bludgeoning.' }, { name: 'Whelm (Recharge 4–6)', description: 'Engulfs creatures in its space (DC 15 STR save, 2d8+4 bludgeoning, grappled & may drown).' }], abilities: [{ name: 'Water Form', description: 'Can move through any space as narrow as 1 inch without squeezing.' }] },
  { name: 'Young Red Dragon', creatureType: 'dragon', level: 10, maxHp: 178, armorClass: 18, speed: '40 ft., fly 80 ft.', stats: { STR: 23, DEX: 10, CON: 21, INT: 14, WIS: 11, CHA: 19 }, resistances: ['fire'], weaknesses: [], actions: [{ name: 'Multiattack', description: 'Makes one bite and two claw attacks.' }, { name: 'Bite', description: '+10 to hit, 2d10+6 piercing plus 1d6 fire.' }, { name: 'Claw', description: '+10 to hit, 2d6+6 slashing.' }, { name: 'Fire Breath (Recharge 5–6)', description: '30-ft cone, DC 17 DEX save, 16d6 fire (half on save).' }], abilities: [{ name: 'Immunities', description: 'Immune to fire damage.' }] },
];

/** Pick an emoji icon from a creature's name/type. */
export function iconForCreature(name: string, type: string): string {
  const s = `${name} ${type}`.toLowerCase();
  const map: [RegExp, string][] = [
    [/dragon/, '🐉'],
    [/skeleton|specter|wight|lich/, '💀'],
    [/zombie/, '🧟'],
    [/ghost|wisp|spectre/, '👻'],
    [/ghoul|undead/, '🧟'],
    [/goblin|kobold/, '👺'],
    [/orc|hobgoblin|bugbear|gnoll/, '🧌'],
    [/ogre|troll|giant/, '🗿'],
    [/wolf/, '🐺'],
    [/bear|owlbear/, '🐻'],
    [/spider/, '🕷️'],
    [/rat/, '🐀'],
    [/bat/, '🦇'],
    [/boar|pig/, '🐗'],
    [/snake|serpent/, '🐍'],
    [/fire|flame/, '🔥'],
    [/water|aqua/, '🌊'],
    [/devil|demon|fiend|imp|quasit/, '😈'],
    [/ooze|cube|slime|jelly/, '🟩'],
    [/armor|construct|golem/, '🛡️'],
    [/mimic/, '🧰'],
    [/bandit|guard|cultist|humanoid/, '🧑'],
  ];
  for (const [re, emoji] of map) if (re.test(s)) return emoji;
  return '👹';
}

const toTemplate = (e: SrdEntry): CreatureTemplate => ({
  name: e.name,
  creatureType: e.creatureType,
  level: e.level,
  maxHp: e.maxHp,
  armorClass: e.armorClass,
  speed: e.speed,
  stats: e.stats,
  resistances: e.resistances,
  weaknesses: e.weaknesses,
  actions: e.actions,
  abilities: e.abilities,
  icon: iconForCreature(e.name, e.creatureType),
  source: 'srd',
});

/** Fuzzy-ish prefix/substring search over the local SRD list. */
export function searchSrd(query: string, limit = 8): CreatureTemplate[] {
  const q = query.trim().toLowerCase();
  if (!q) return SRD.slice(0, limit).map(toTemplate);
  const matches = SRD.filter((e) => e.name.toLowerCase().includes(q));
  matches.sort((a, b) => {
    const ap = a.name.toLowerCase().startsWith(q) ? 0 : 1;
    const bp = b.name.toLowerCase().startsWith(q) ? 0 : 1;
    return ap - bp || a.name.localeCompare(b.name);
  });
  return matches.slice(0, limit).map(toTemplate);
}

/** Exact (case-insensitive) SRD lookup. */
export function getSrd(name: string): CreatureTemplate | null {
  const e = SRD.find((m) => m.name.toLowerCase() === name.trim().toLowerCase());
  return e ? toTemplate(e) : null;
}

/** All SRD creatures (used by the completeness test / diagnostics). */
export function allSrd(): CreatureTemplate[] {
  return SRD.map(toTemplate);
}

/**
 * Find the SRD "base" creature a custom/themed name extends, so the AI can scale
 * UP from it (a "Stone Goblin" / "Blood Goblin" → the Goblin block as a floor).
 * Matches the LONGEST SRD name that appears as a whole word in the query, while
 * ignoring an exact match (that's handled by getSrd). Null if nothing matches.
 */
export function findBaseCreature(name: string): CreatureTemplate | null {
  const q = name.trim().toLowerCase();
  if (!q) return null;
  let best: SrdEntry | null = null;
  for (const e of SRD) {
    const n = e.name.toLowerCase();
    if (n === q) continue; // exact → not a variant
    const safe = n.replace(/[-/\\^$*+?.()|[\]{}']/g, '\\$&');
    if (new RegExp(`\\b${safe}\\b`).test(q) && (!best || n.length > best.name.length)) best = e;
  }
  return best ? toTemplate(best) : null;
}
