import {readFileSync,writeFileSync} from 'node:fs';
import {test,expect} from '@playwright/test';
import {io,type Socket} from 'socket.io-client';
import {DM_SECRET,PORT} from './playwright.config';
import type {StateSnapshot} from '../shared/types';
import {expectUnclipped} from './helpers/rollVisibility';
import {startAv1Capture} from './directAv1Recorder';
test.use({deviceScaleFactor:1});
test('hidden attacks, damage, saves and checks await private DM approval in the same tray',async({page,browser,request})=>{
 test.setTimeout(240000);
 const {code}=await(await request.post('/api/sessions',{headers:{'x-dm-passphrase':DM_SECRET},data:{name:'Private DM approval'}})).json();
 const sockets:Socket[]=[];
 const dm=io(`http://localhost:${PORT}`,{transports:['websocket'],forceNew:true});sockets.push(dm);
 const observer=io(`http://localhost:${PORT}`,{transports:['websocket'],forceNew:true});sockets.push(observer);
 const snapshot=async():Promise<StateSnapshot>=>(await dm.timeout(5000).emitWithAck('join',{sessionCode:code,role:'dm',dmPassphrase:DM_SECRET})).snapshot;
 const playerContext=await browser.newContext({viewport:{width:1600,height:1000}}),player=await playerContext.newPage();
 let capture:Awaited<ReturnType<typeof startAv1Capture>>|undefined;
 try{
 const druk=(await snapshot()).characters.find(c=>c.name==='Druk')!;
 dm.emit('character:update',{characterId:druk.id,className:'Fighter',level:3,armorClass:12,maxHp:40,curHp:40,stats:{STR:18,DEX:12,CON:14,INT:10,WIS:10,CHA:10}});
 dm.emit('session:setManualDamage',{manual:true});
 const map=await(await request.post(`/api/sessions/${code}/maps`,{headers:{'x-dm-passphrase':DM_SECRET},multipart:{name:'Courtyard',image:{name:'courtyard.png',mimeType:'image/png',buffer:readFileSync('assets/environment-preview/courtyard.png')}}})).json();
 dm.emit('map:setActive',{mapId:map.id});dm.emit('map:setGrid',{mapId:map.id,gridSizePx:64,feetPerSquare:5,widthFt:100,locked:false});
 dm.emit('fog:setLayer',{mapId:map.id,layer:'map',enabled:false});dm.emit('fog:setLayer',{mapId:map.id,layer:'tokens',enabled:false});
 dm.emit('token:spawn',{mapId:map.id,kind:'pc',refId:druk.id,x:600,y:540});
 dm.emit('monster:create',{name:'Goblin',modelType:'goblin',disposition:'enemy',maxHp:40,armorClass:12,stats:{STR:12,DEX:14,CON:10,INT:8,WIS:10,CHA:8},weapons:[{name:'Scimitar',kind:'melee',damage:'1d6+2',damageType:'slashing',attackBonus:5}]});
 const template=(await snapshot()).monsterTemplates.find(m=>m.name==='Goblin')!;
 dm.emit('token:spawn',{mapId:map.id,kind:'monster',refId:template.id,x:635,y:480});
 const setup=await snapshot(),pc=setup.tokens.find(t=>t.kind==='pc')!,enemy=setup.tokens.find(t=>t.kind==='monster')!;
 const playerFrames:any[]=[],playerReviews:any[]=[],playerHp:any[]=[];
 observer.on('dice:frame',f=>playerFrames.push(f));observer.on('dice:hiddenReview',r=>playerReviews.push(r));observer.on('fx:hp',e=>playerHp.push(e));
 await observer.timeout(5000).emitWithAck('join',{sessionCode:code,role:'player'});
 await player.goto(`/join?code=${code}`);await player.getByRole('button',{name:'Join',exact:true}).click();await player.locator('.claim-row').filter({hasText:'Druk'}).click();
 await page.setViewportSize({width:1600,height:1000});await page.goto(`/dm?code=${code}`);
 await page.locator('input[type=password]').fill(DM_SECRET);await page.getByRole('button',{name:'Rejoin as DM',exact:true}).click();
 await page.getByRole('button',{name:'Chat & dice',exact:true}).click();await page.locator('.chat-dice-options > summary').click();
 await page.getByRole('button',{name:/DM rolls shown/}).click();
 expect((await snapshot()).hideDmRolls).toBe(true);
 await page.getByRole('button',{name:'Close DM panel',exact:true}).click();
 await expect(page.getByTestId('miniature-layer')).toHaveAttribute('data-miniature-count','2',{timeout:60000});
 await page.waitForFunction(()=>JSON.parse(document.documentElement.dataset.dicePreloadedThemes??'[]').some((id:string)=>id.startsWith('dm-')),{},{timeout:45000});
 await page.bringToFront();await page.evaluate(()=>document.title='Druk Direct AV1 Recording');
 if(process.env.HIDDEN_REVIEW_VIDEO){
  capture=await startAv1Capture(page,process.env.HIDDEN_REVIEW_VIDEO);
 }
 const point=(id:string)=>page.evaluate(id=>{const s=(window as any).Konva.stages.find((s:any)=>s.find('.token').some((n:any)=>n.getAttr('tokenId')===id)),n=s.find('.token').find((n:any)=>n.getAttr('tokenId')===id),p=n.getAbsolutePosition(),r=s.container().getBoundingClientRect();return{x:r.left+p.x,y:r.top+p.y};},id);
 const review=page.getByRole('region',{name:'Approve hidden result'});
 let attack:any;
  const b=await point(enemy.id),p=await point(pc.id);
  await page.mouse.move(b.x,b.y,{steps:16});await page.mouse.click(b.x,b.y);
  await page.mouse.move(p.x,p.y,{steps:16});await page.mouse.click(p.x,p.y,{button:'right'});
  await page.getByRole('dialog',{name:'Token actions'}).getByRole('button',{name:/Scimitar/}).click();
  await expect(review).toBeVisible({timeout:30000});
  await expect(page.locator('.roll-reveal-backdrop')).toBeVisible();
  await expect(page.locator('dialog.hidden-roll-review')).toHaveCount(0);
  const trayCanvas=await page.locator('.dice-tray-canvas').elementHandle();
  const rollBounds=await page.locator('.roll-reveal-backdrop > .roll-reveal').boundingBox();
  const visibleTray=await page.locator('.dice-tray-stage').boundingBox();
  expect(visibleTray!.width).toBeGreaterThanOrEqual(740);
  expect(visibleTray!.height).toBeGreaterThanOrEqual(495);
  const attackReviewId=await review.getAttribute('data-review-id');
  expect((await snapshot()).rollLog).toHaveLength(0);
  expect((await snapshot()).characters.find(c=>c.id===druk.id)!.curHp).toBe(40);
  expect(playerFrames).toHaveLength(0);expect(playerReviews).toHaveLength(0);expect(playerHp).toHaveLength(0);
  await expect(player.locator('.roll-reveal-backdrop')).toHaveCount(0);
  await review.getByRole('button',{name:'Reject & reroll',exact:true}).click();
  await expect(review).not.toHaveAttribute('data-review-id',attackReviewId!,{timeout:30000});
  expect(await trayCanvas!.evaluate(node=>node===document.querySelector('.dice-tray-canvas'))).toBe(true);
  expect(await page.locator('.roll-reveal-backdrop > .roll-reveal').boundingBox()).toEqual(rollBounds);
  expect((await snapshot()).rollLog).toHaveLength(0);
  await review.getByRole('button',{name:'Enter result',exact:true}).click();
  await review.getByLabel('Final total (includes modifiers)',{exact:true}).fill('17');
  await review.getByRole('button',{name:'Review entered result',exact:true}).click();
  await expect(review).toContainText('Total 17');
  await expect(review.locator('[data-outcome=hit]')).toHaveText('Hit');
  expect((await snapshot()).rollLog).toHaveLength(0);
  expect((await observer.timeout(5000).emitWithAck('join',{sessionCode:code,role:'player'})).snapshot.rollLog).toEqual([]);
  await review.getByRole('button',{name:'Apply result',exact:true}).click();
  await expect(review).toHaveCount(0);
  await expect.poll(async()=>(await snapshot()).rollLog.length).toBe(1);
  attack=(await snapshot()).rollLog.at(-1);
 expect(attack?.pending).toBeTruthy();
 await expect(page.locator('.damage-prompt:not(.spell-prompt) .damage-prompt-btn')).toBeVisible({timeout:30000});
 // This button intentionally pulses; click its visible centre instead of
 // waiting for the animated transform to become stationary in headed capture.
 const damageButton=await page.locator('.damage-prompt:not(.spell-prompt) .damage-prompt-btn').boundingBox();
 expect(damageButton).toBeTruthy();
 await page.mouse.move(damageButton!.x+damageButton!.width/2,damageButton!.y+damageButton!.height/2,{steps:16});
 await page.mouse.click(damageButton!.x+damageButton!.width/2,damageButton!.y+damageButton!.height/2);
 await expect(review).toBeVisible({timeout:30000});
 await expect(review).toContainText('Damage');
 const damageReviewId=await review.getAttribute('data-review-id');
 const damageCanvas=await page.locator('.dice-tray-canvas').elementHandle();
 const damageBounds=await page.locator('.roll-reveal-backdrop > .roll-reveal').boundingBox();
 expect((await snapshot()).characters.find(c=>c.id===druk.id)!.curHp).toBe(40);
 expect((await snapshot()).rollLog).toHaveLength(1);expect(playerHp).toHaveLength(0);
 expect(playerFrames).toHaveLength(0);expect(playerReviews).toHaveLength(0);
 await expect(player.locator('.roll-reveal-backdrop')).toHaveCount(0);
 await review.getByRole('button',{name:'Reject & reroll',exact:true}).click();
 await expect(review).not.toHaveAttribute('data-review-id',damageReviewId!,{timeout:30000});
 expect(await damageCanvas!.evaluate(node=>node===document.querySelector('.dice-tray-canvas'))).toBe(true);
 expect(await page.locator('.roll-reveal-backdrop > .roll-reveal').boundingBox()).toEqual(damageBounds);
 expect((await snapshot()).characters.find(c=>c.id===druk.id)!.curHp).toBe(40);
 expect((await snapshot()).rollLog).toHaveLength(1);expect(playerHp).toHaveLength(0);
 await review.getByRole('button',{name:'Enter result',exact:true}).click();
 await review.locator('input[type=number]').fill('4');
 await review.getByRole('button',{name:'Review entered result',exact:true}).click();
 await expect(review).toContainText('DM-entered result');
 expect((await snapshot()).characters.find(c=>c.id===druk.id)!.curHp).toBe(40);
 await review.getByRole('button',{name:'Apply result',exact:true}).click();
 await expect.poll(async()=>(await snapshot()).characters.find(c=>c.id===druk.id)!.curHp,{timeout:30000}).toBeLessThan(40);
 await expect(review).toHaveCount(0);
 const resolved=(await snapshot()).rollLog.find(r=>r.id===attack.id)!;
 expect(40-(await snapshot()).characters.find(c=>c.id===druk.id)!.curHp).toBe(resolved.pending!.amount);
 await expect.poll(()=>playerHp.length).toBeGreaterThan(0);
 expect(playerFrames).toHaveLength(0);expect(playerReviews).toHaveLength(0);
 await expect(player.locator('.roll-reveal-backdrop')).toHaveCount(0);
 await player.screenshot({path:test.info().outputPath('player-hidden-attack-damage.png')});
 // The DM rolls a save separately, through the selected creature's stat block.
 const info=page.locator('.reorder-section').filter({has:page.getByRole('heading',{name:'Token info',exact:true})});
 const expand=info.getByTitle('Expand section', {exact:true});if(await expand.isVisible())await expand.click();
 await info.locator('.sb-ability-roll').filter({hasText:'STR'}).click();
 const oldCount=(await snapshot()).rollLog.length;
 const playerLogBefore=(await observer.timeout(5000).emitWithAck('join',{sessionCode:code,role:'player'})).snapshot.rollLog;
 await info.getByTitle('STR saving throw (adds proficiency if proficient)',{exact:true}).click();
 const startSave=page.getByRole('button',{name:'Roll saving throw',exact:true});
 await expect(startSave).toBeVisible({timeout:30000});
 await expect(page.getByRole('region',{name:'Saving throw needed'})).toContainText('STR');
 await expect(page.getByRole('region',{name:'Saving throw needed'})).toContainText('Goblin');
 await expect(page.getByRole('status',{name:'Live dice roll',exact:true})).toBeHidden();
 await expectUnclipped(startSave);
 const waitingTray=page.locator('[data-awaiting-start=true]');
 const saveTrayId=await waitingTray.getAttribute('data-roll-id');
 observer.emit('dice:begin',{id:saveTrayId});dm.emit('dice:begin',{id:saveTrayId});
 // A graphics-ready fallback or a different DM connection must not start it.
 await page.waitForTimeout(16000);await expect(startSave).toBeVisible();
 await expect(waitingTray).toHaveAttribute('data-awaiting-start','true');
 expect((await snapshot()).rollLog).toHaveLength(oldCount);
 const saveCanvas=await page.locator('.dice-tray-canvas').elementHandle();
 const saveBounds=await page.locator('.roll-reveal-backdrop > .roll-reveal').boundingBox();
 await startSave.click();
 await expect(review).toBeVisible({timeout:30000});await expect(review).toContainText(/STR/i);
 expect(await saveCanvas!.evaluate(node=>node===document.querySelector('.dice-tray-canvas'))).toBe(true);
 expect(await page.locator('.roll-reveal-backdrop > .roll-reveal').boundingBox()).toEqual(saveBounds);
 await expect(page.locator('.dice-tray-canvas')).toBeVisible();
 await expect(review.locator('.hidden-roll-details')).not.toHaveAttribute('open','');
 expect(await review.locator('.hidden-roll-who').evaluate(n=>parseFloat(getComputedStyle(n).fontSize))).toBeGreaterThanOrEqual(22);
 await expectUnclipped(review.getByRole('button',{name:'Apply result'}));
 await expectUnclipped(review.getByRole('button',{name:'Reject & reroll'}));
 await expectUnclipped(review.locator('.hidden-roll-verdict'));
 expect((await snapshot()).rollLog).toHaveLength(oldCount);
 const hpEvents=playerHp.length;
 expect((await observer.timeout(5000).emitWithAck('join',{sessionCode:code,role:'player'})).snapshot.rollLog).toEqual(playerLogBefore);
 const id=await page.evaluate(()=>new Promise<string>(resolve=>{
  // The ID is read from the native confirmation UI's server-driven attribute.
  resolve(document.querySelector('.hidden-roll-review')!.getAttribute('data-review-id')!);
 }));
 observer.emit('dice:confirmHidden',{id,apply:true});dm.emit('dice:confirmHidden',{id,apply:true});
 await page.waitForTimeout(500);await expect(review).toBeVisible();
 expect((await snapshot()).rollLog).toHaveLength(oldCount);
 expect(playerHp).toHaveLength(hpEvents);expect(playerFrames).toHaveLength(0);
 // Rejecting rerolls the same pending save; entering a total recalculates it,
 // and neither action resolves the step or publishes anything to players.
 await review.getByRole('button',{name:'Reject & reroll',exact:true}).click();
 await expect(review).not.toHaveAttribute('data-review-id',id,{timeout:30000});
 await expect(review.getByRole('button',{name:'Apply result'})).toBeEnabled();
 expect((await snapshot()).rollLog).toHaveLength(oldCount);
 await review.getByRole('button',{name:'Enter result',exact:true}).click();
 await review.getByLabel('Final total (includes modifiers)',{exact:true}).fill('18');
 await review.getByRole('button',{name:'Review entered result',exact:true}).click();
 await expect(review).toContainText('DM-entered result');await expect(review).toContainText('Total 18');
 await page.setViewportSize({width:412,height:915});
 expect((await review.boundingBox())!.width).toBeLessThan(412);
 expect((await page.locator('.dice-tray-stage').boundingBox())!.width).toBeGreaterThanOrEqual(350);
 await expectUnclipped(review.getByRole('button',{name:'Apply result'}));
 await expectUnclipped(review.getByRole('button',{name:'Reject & reroll'}));
 await expectUnclipped(review.locator('.hidden-roll-verdict'));
 await page.screenshot({path:test.info().outputPath('phone-private-review.png')});
 await page.setViewportSize({width:1600,height:1000});
 expect((await snapshot()).rollLog).toHaveLength(oldCount);
 expect((await observer.timeout(5000).emitWithAck('join',{sessionCode:code,role:'player'})).snapshot.rollLog).toEqual(playerLogBefore);
 await page.screenshot({path:test.info().outputPath('dm-private-save-approval.png')});
 await player.screenshot({path:test.info().outputPath('player-before-approval.png')});
 await page.waitForTimeout(1500);await review.getByRole('button',{name:'Apply result'}).click();await expect(review).toHaveCount(0);
 await expect.poll(async()=>(await snapshot()).rollLog.length).toBe(oldCount+1);
 expect(playerFrames).toHaveLength(0);expect(playerReviews).toHaveLength(0);
 await expect(player.locator('.roll-reveal-backdrop')).toHaveCount(0);
 await page.waitForTimeout(1500);await player.screenshot({path:test.info().outputPath('player-approved-damage.png')});
 await page.waitForTimeout(3500);
 if(capture){console.log(await capture.stop());capture=undefined;}
 // Check the native discard control independently of attack/damage follow-ups.
 await page.getByRole('button',{name:'Chat & dice',exact:true}).click();
 if(!await page.locator('.dice-row input[placeholder="2d6+3"]').isVisible())await page.locator('.chat-dice-options > summary').click();
 const beforeDiscard=(await snapshot()).rollLog.length;
 await page.locator('.dice-row input[placeholder="2d6+3"]').fill('1d20+7');
 await page.locator('.dice-row').getByRole('button',{name:'Roll',exact:true}).click();
 await expect(review).toBeVisible({timeout:30000});await expect(review).toContainText('7');
 await review.getByRole('button',{name:'Discard result'}).click();await expect(review).toHaveCount(0);
 expect((await snapshot()).rollLog).toHaveLength(beforeDiscard);
 const visible=(await observer.timeout(5000).emitWithAck('join',{sessionCode:code,role:'player'})).snapshot;
 expect(visible.rollLog.length).toBeGreaterThan(0);
 expect(visible.rollLog.every(r=>r.outcomeOnly&&r.hideTotal&&!r.reveal&&!r.expr&&!r.description&&!r.pending&&!r.apply)).toBe(true);
 const saveSummary=visible.rollLog.find(r=>r.label==='STR save')!;
 expect(saveSummary.detail).toContain('Resolved');
 expect(saveSummary.detail).not.toMatch(/18|15|\+|prof|DC|d20/i);
 expect(visible.rollLog.find(r=>r.label==='Damage')?.detail).toContain(`${resolved.pending!.amount} slashing damage`);
 await expect(player.locator('.roll-reveal-backdrop')).toHaveCount(0);
 await test.info().attach('approved-hidden-damage',{body:JSON.stringify({attack:resolved,hp:40-resolved.pending!.amount,playerDiceFrames:playerFrames.length,playerReviewMessages:playerReviews.length}),contentType:'application/json'});
 if(process.env.HIDDEN_REVIEW_VIDEO)writeFileSync(process.env.HIDDEN_REVIEW_VIDEO+'.evidence.json',JSON.stringify({attack:resolved,hpBefore:40,hpAfter:40-resolved.pending!.amount,playerDiceFrames:playerFrames.length,playerReviewMessages:playerReviews.length},null,2));
 }finally{if(capture)await capture.stop();sockets.forEach(s=>s.disconnect());await playerContext.close();}
});
